package Enums;

public enum Categoria {
    MEJOR_PELICULA,
    MEJOR_DIRECTOR,
    MEJOR_ACTOR,
    MEJOR_ACTRIZ,
    MEJOR_ACTOR_REPARTO,
    MEJOR_ACTRIZ_REPARTO,
    MEJOR_GUION,
    MEJOR_BANDA_SONORA,
    MEJOR_DISENIO_DE_PRODUCCION,
    MEJOR_DOCUMENTAL,
    MEJOR_PELICULA_ANIMADA,
    PREMIO_DEL_PUBLICO
}
